permalink: /:title
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
pygments: true
markdown: kramdown

title : 深圳南山律师事务所
tagline : 深圳贤耀律师事务所
author : 
  name : xylawyer
  email : blah@email.test
  github : xylawyer
  twitter : username
  feedburner : feedname

uction_url : http://xylawyer.github.io

JB :
  version : 0.3.0
  BASE_PATH : false
  ASSET_PATH : false
  archive_path: /archive.html
  categories_path : /categories.html
  tags_path : /tags.html
  atom_path : /atom.xml
  rss_path : /rss.xml
